name: Algolia Docsearch Action

on:
  push:
    paths:
      - "**.md"
      - docsearch.json

jobs:
  algolia:
    runs-on: ubuntu-latest
    name: algolia-crawler
    steps:
      - uses: actions/checkout@v2
      - name: crawling
        uses: guzhongren/algolia-docsearch-upload-action@v2.0.0
        env:
          ADMIN_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
          APPLICATION_ID: ${{ secrets.ALGOLIA_APPLICATION_ID }}
          FILE_PATH: docsearch.json
          INDEX_NAME: "doc"
