name: Algolia Docsearch Action

on:
  push:
    paths:
      - "**.md"
      - docsearch.json

jobs:
  algolia:
    runs-on: ubuntu-latest
    name: algolia-crawler
    steps:
      - uses: actions/checkout@v2
      - name: crawling
        uses: darrenjennings/algolia-docsearch-action@master
        with:
          algolia_api_key: ${{ secrets.ALGOLIA_API_KEY }}
          algolia_application_id: ${{ secrets.ALGOLIA_APPLICATION_ID }}
          file: docsearch.json
